/**
 * Demo detections — realistic-looking oil slick records spread across
 * Australian and Pacific waters, used as a client-visible fallback when the
 * database is empty (initial deploy, local dev without seeds, etc.).
 *
 * Timestamps are computed relative to Date.now() at call time so "fresh"
 * detections always appear within the last 24 h and pulse correctly.
 */

import type { DetectionFeatureCollection, DetectionFeature } from './detections';
import type { MultiPolygon } from 'geojson';

const MIN = 60 * 1000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

function ago(ms: number): string {
  return new Date(Date.now() - ms).toISOString();
}

function rect(lon: number, lat: number, w: number, h: number): MultiPolygon {
  return {
    type: 'MultiPolygon',
    coordinates: [
      [
        [
          [lon, lat],
          [lon + w, lat],
          [lon + w, lat - h],
          [lon, lat - h],
          [lon, lat],
        ],
      ],
    ],
  };
}

function isFreshAge(ms: number): boolean {
  return ms < DAY;
}

export function getDemoDetections(): DetectionFeatureCollection {
  const features: DetectionFeature[] = [
    // ── Very fresh (< 2 h) — strong pulse ───────────────────────────────────

    {
      type: 'Feature',
      geometry: rect(141.3, -9.9, 0.5, 0.4),
      properties: {
        id: 'demo-torres-fresh',
        source: 'demo',
        source_record_id: 'DEMO-TORRES-FRESH',
        acquisition_id: 'S1B_IW_GRDH_DEMO_TORRES',
        detected_at: ago(35 * MIN),
        ingested_at: ago(25 * MIN),
        area_km2: 18,
        confidence: 0.12,
        confidence_tier: 'anomaly',
        pollutant_type: 'oil',
        provenance: 'heuristic-v0',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'heuristic-v0',
        metadata: { zone: 'Torres Strait', notes: 'Demo — unvalidated SAR anomaly' },
        is_fresh: isFreshAge(35 * MIN),
        is_experimental: true,
      },
    },

    {
      type: 'Feature',
      geometry: rect(136.3, -13.4, 0.7, 0.55),
      properties: {
        id: 'demo-carpentaria-fresh',
        source: 'demo',
        source_record_id: 'DEMO-CARPENTARIA-FRESH',
        acquisition_id: 'S1A_IW_GRDH_DEMO_CARP',
        detected_at: ago(1.1 * HOUR),
        ingested_at: ago(50 * MIN),
        area_km2: 32,
        confidence: 0.08,
        confidence_tier: 'anomaly',
        pollutant_type: 'oil',
        provenance: 'heuristic-v0',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'heuristic-v0',
        metadata: { zone: 'Gulf of Carpentaria', notes: 'Demo — unvalidated SAR anomaly' },
        is_fresh: isFreshAge(1.1 * HOUR),
        is_experimental: true,
      },
    },

    {
      type: 'Feature',
      geometry: rect(150.7, -35.0, 0.4, 0.3),
      properties: {
        id: 'demo-jervis-fresh',
        source: 'demo',
        source_record_id: 'DEMO-JERVIS-FRESH',
        acquisition_id: 'S1A_IW_GRDH_DEMO_JERVIS',
        detected_at: ago(45 * MIN),
        ingested_at: ago(35 * MIN),
        area_km2: 12,
        confidence: 0.09,
        confidence_tier: 'anomaly',
        pollutant_type: 'oil',
        provenance: 'heuristic-v0',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'heuristic-v0',
        metadata: { zone: 'Jervis Bay', notes: 'Demo — unvalidated SAR anomaly' },
        is_fresh: isFreshAge(45 * MIN),
        is_experimental: true,
      },
    },

    // ── Fresh (2–24 h) — pulse ───────────────────────────────────────────────

    {
      type: 'Feature',
      geometry: rect(123.5, -12.3, 1.2, 0.9),
      properties: {
        id: 'demo-timor-verified',
        source: 'demo',
        source_record_id: 'DEMO-TIMOR-VERIFIED',
        acquisition_id: 'S1A_IW_GRDH_DEMO_TIMOR',
        detected_at: ago(2 * HOUR),
        ingested_at: ago(1.5 * HOUR),
        area_km2: 1850,
        confidence: 0.93,
        confidence_tier: 'verified',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Timor Sea', notes: 'Demo — high-confidence SAR detection' },
        is_fresh: isFreshAge(2 * HOUR),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(146.4, -39.5, 0.9, 0.65),
      properties: {
        id: 'demo-bass-verified',
        source: 'demo',
        source_record_id: 'DEMO-BASS-VERIFIED',
        acquisition_id: 'S1B_IW_GRDH_DEMO_BASS',
        detected_at: ago(12 * HOUR),
        ingested_at: ago(11.5 * HOUR),
        area_km2: 410,
        confidence: 0.91,
        confidence_tier: 'verified',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: {
          zone: 'Bass Strait',
          notes: 'Demo — confirmed oil slick near production platform',
        },
        is_fresh: isFreshAge(12 * HOUR),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(151.7, -34.1, 0.6, 0.45),
      properties: {
        id: 'demo-sydney-verified',
        source: 'demo',
        source_record_id: 'DEMO-SYDNEY-VERIFIED',
        acquisition_id: 'S1A_IW_GRDH_DEMO_SYDNEY',
        detected_at: ago(6 * HOUR),
        ingested_at: ago(5.5 * HOUR),
        area_km2: 95,
        confidence: 0.88,
        confidence_tier: 'verified',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Sydney offshore', notes: 'Demo — vessel discharge detection' },
        is_fresh: isFreshAge(6 * HOUR),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(115.3, -19.6, 1.0, 0.8),
      properties: {
        id: 'demo-nwshelf-probable',
        source: 'demo',
        source_record_id: 'DEMO-NWSHELF-PROBABLE',
        acquisition_id: 'S1A_IW_GRDH_DEMO_NWS',
        detected_at: ago(6.5 * HOUR),
        ingested_at: ago(6 * HOUR),
        area_km2: 340,
        confidence: 0.72,
        confidence_tier: 'probable',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'NW Shelf (Barrow Island)', notes: 'Demo — probable oil sheen' },
        is_fresh: isFreshAge(6.5 * HOUR),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(130.6, -12.3, 0.5, 0.4),
      properties: {
        id: 'demo-darwin-possible',
        source: 'demo',
        source_record_id: 'DEMO-DARWIN-POSSIBLE',
        acquisition_id: 'S1B_IW_GRDH_DEMO_DARWIN',
        detected_at: ago(2.2 * HOUR),
        ingested_at: ago(2 * HOUR),
        area_km2: 52,
        confidence: 0.41,
        confidence_tier: 'possible',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Darwin Harbour approaches', notes: 'Demo — possible vessel discharge' },
        is_fresh: isFreshAge(2.2 * HOUR),
        is_experimental: false,
      },
    },

    // ── Recent (1–7 days) ────────────────────────────────────────────────────

    {
      type: 'Feature',
      geometry: rect(151.3, -16.0, 1.1, 0.8),
      properties: {
        id: 'demo-coral-probable',
        source: 'demo',
        source_record_id: 'DEMO-CORAL-PROBABLE',
        acquisition_id: 'S1A_IW_GRDH_DEMO_CORAL',
        detected_at: ago(1 * DAY),
        ingested_at: ago(23 * HOUR),
        area_km2: 480,
        confidence: 0.67,
        confidence_tier: 'probable',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Coral Sea', notes: 'Demo — shipping lane anomaly' },
        is_fresh: isFreshAge(1 * DAY),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(145.3, -17.6, 0.8, 0.6),
      properties: {
        id: 'demo-gbr-possible',
        source: 'demo',
        source_record_id: 'DEMO-GBR-POSSIBLE',
        acquisition_id: 'S1B_IW_GRDH_DEMO_GBR',
        detected_at: ago(3 * DAY),
        ingested_at: ago(3 * DAY - HOUR),
        area_km2: 140,
        confidence: 0.38,
        confidence_tier: 'possible',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Great Barrier Reef (central)', notes: 'Demo — possible surface sheen' },
        is_fresh: isFreshAge(3 * DAY),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(128.3, -13.6, 0.7, 0.55),
      properties: {
        id: 'demo-jbg-anomaly',
        source: 'demo',
        source_record_id: 'DEMO-JBG-ANOMALY',
        acquisition_id: 'S1A_IW_GRDH_DEMO_JBG',
        detected_at: ago(3.5 * DAY),
        ingested_at: ago(3.5 * DAY - HOUR),
        area_km2: 25,
        confidence: 0.11,
        confidence_tier: 'anomaly',
        pollutant_type: 'oil',
        provenance: 'heuristic-v0',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'heuristic-v0',
        metadata: { zone: 'Joseph Bonaparte Gulf', notes: 'Demo — unvalidated SAR anomaly' },
        is_fresh: isFreshAge(3.5 * DAY),
        is_experimental: true,
      },
    },

    {
      type: 'Feature',
      geometry: rect(152.8, -26.3, 0.9, 0.7),
      properties: {
        id: 'demo-seqld-possible',
        source: 'demo',
        source_record_id: 'DEMO-SEQLD-POSSIBLE',
        acquisition_id: 'S1B_IW_GRDH_DEMO_SEQLD',
        detected_at: ago(5 * DAY),
        ingested_at: ago(5 * DAY - HOUR),
        area_km2: 210,
        confidence: 0.44,
        confidence_tier: 'possible',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'SE Queensland coast', notes: 'Demo — coastal discharge investigation' },
        is_fresh: isFreshAge(5 * DAY),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(136.0, -33.8, 0.6, 0.5),
      properties: {
        id: 'demo-spencer-anomaly',
        source: 'demo',
        source_record_id: 'DEMO-SPENCER-ANOMALY',
        acquisition_id: 'S1A_IW_GRDH_DEMO_SPENCER',
        detected_at: ago(4 * DAY),
        ingested_at: ago(4 * DAY - HOUR),
        area_km2: 18,
        confidence: 0.14,
        confidence_tier: 'anomaly',
        pollutant_type: 'oil',
        provenance: 'heuristic-v0',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'heuristic-v0',
        metadata: { zone: 'Spencer Gulf', notes: 'Demo — unvalidated SAR anomaly' },
        is_fresh: isFreshAge(4 * DAY),
        is_experimental: true,
      },
    },

    {
      type: 'Feature',
      geometry: rect(133.3, -10.3, 0.8, 0.6),
      properties: {
        id: 'demo-arafura-anomaly',
        source: 'demo',
        source_record_id: 'DEMO-ARAFURA-ANOMALY',
        acquisition_id: 'S1B_IW_GRDH_DEMO_ARAFURA',
        detected_at: ago(5.5 * DAY),
        ingested_at: ago(5.5 * DAY - HOUR),
        area_km2: 38,
        confidence: 0.09,
        confidence_tier: 'anomaly',
        pollutant_type: 'oil',
        provenance: 'heuristic-v0',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'heuristic-v0',
        metadata: { zone: 'Arafura Sea', notes: 'Demo — unvalidated SAR anomaly' },
        is_fresh: isFreshAge(5.5 * DAY),
        is_experimental: true,
      },
    },

    {
      type: 'Feature',
      geometry: rect(144.6, -38.4, 0.7, 0.55),
      properties: {
        id: 'demo-portphillip-possible',
        source: 'demo',
        source_record_id: 'DEMO-PORTPHILLIP-POSSIBLE',
        acquisition_id: 'S1B_IW_GRDH_DEMO_PPB',
        detected_at: ago(2 * DAY),
        ingested_at: ago(2 * DAY - HOUR),
        area_km2: 78,
        confidence: 0.52,
        confidence_tier: 'possible',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Port Phillip approaches', notes: 'Demo — possible vessel discharge' },
        is_fresh: isFreshAge(2 * DAY),
        is_experimental: false,
      },
    },

    // ── Older (7–30 days) ────────────────────────────────────────────────────

    {
      type: 'Feature',
      geometry: rect(112.3, -31.3, 0.9, 0.7),
      properties: {
        id: 'demo-perth-possible',
        source: 'demo',
        source_record_id: 'DEMO-PERTH-POSSIBLE',
        acquisition_id: 'S1A_IW_GRDH_DEMO_PERTH',
        detected_at: ago(7 * DAY),
        ingested_at: ago(7 * DAY - HOUR),
        area_km2: 165,
        confidence: 0.35,
        confidence_tier: 'possible',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Perth Canyon', notes: 'Demo — possible oil sheen' },
        is_fresh: isFreshAge(7 * DAY),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(157.3, -35.0, 1.2, 0.9),
      properties: {
        id: 'demo-tasman-probable',
        source: 'demo',
        source_record_id: 'DEMO-TASMAN-PROBABLE',
        acquisition_id: 'S1A_IW_GRDH_DEMO_TASMAN',
        detected_at: ago(8 * DAY),
        ingested_at: ago(8 * DAY - HOUR),
        area_km2: 620,
        confidence: 0.63,
        confidence_tier: 'probable',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Tasman Sea', notes: 'Demo — shipping route detection' },
        is_fresh: isFreshAge(8 * DAY),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(165.3, -21.3, 0.8, 0.6),
      properties: {
        id: 'demo-newcal-probable',
        source: 'demo',
        source_record_id: 'DEMO-NEWCAL-PROBABLE',
        acquisition_id: 'S1A_IW_GRDH_DEMO_NEWCAL',
        detected_at: ago(10 * DAY),
        ingested_at: ago(10 * DAY - HOUR),
        area_km2: 260,
        confidence: 0.69,
        confidence_tier: 'probable',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'New Caledonia EEZ', notes: 'Demo — Pacific shipping route detection' },
        is_fresh: isFreshAge(10 * DAY),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(127.3, -33.6, 1.0, 0.75),
      properties: {
        id: 'demo-gab-anomaly',
        source: 'demo',
        source_record_id: 'DEMO-GAB-ANOMALY',
        acquisition_id: 'S1A_IW_GRDH_DEMO_GAB',
        detected_at: ago(15 * DAY),
        ingested_at: ago(15 * DAY - HOUR),
        area_km2: 48,
        confidence: 0.13,
        confidence_tier: 'anomaly',
        pollutant_type: 'oil',
        provenance: 'heuristic-v0',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'heuristic-v0',
        metadata: { zone: 'Great Australian Bight', notes: 'Demo — unvalidated SAR anomaly' },
        is_fresh: isFreshAge(15 * DAY),
        is_experimental: true,
      },
    },

    {
      type: 'Feature',
      geometry: rect(146.3, -44.3, 0.9, 0.7),
      properties: {
        id: 'demo-tasmania-possible',
        source: 'demo',
        source_record_id: 'DEMO-TASMANIA-POSSIBLE',
        acquisition_id: 'S1B_IW_GRDH_DEMO_TAS',
        detected_at: ago(12 * DAY),
        ingested_at: ago(12 * DAY - HOUR),
        area_km2: 185,
        confidence: 0.34,
        confidence_tier: 'possible',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: {
          zone: 'Southern Ocean approaches (SE Tasmania)',
          notes: 'Demo — possible oil trail',
        },
        is_fresh: isFreshAge(12 * DAY),
        is_experimental: false,
      },
    },

    {
      type: 'Feature',
      geometry: rect(113.6, -21.3, 0.7, 0.55),
      properties: {
        id: 'demo-exmouth-possible',
        source: 'demo',
        source_record_id: 'DEMO-EXMOUTH-POSSIBLE',
        acquisition_id: 'S1B_IW_GRDH_DEMO_EXMOUTH',
        detected_at: ago(20 * DAY),
        ingested_at: ago(20 * DAY - HOUR),
        area_km2: 88,
        confidence: 0.31,
        confidence_tier: 'possible',
        pollutant_type: 'oil',
        provenance: 'cdse-derived',
        thumbnail_url: null,
        raw_record_url: null,
        model_version: 'cdse-v1',
        metadata: { zone: 'Exmouth Gulf', notes: 'Demo — suspected vessel discharge' },
        is_fresh: isFreshAge(20 * DAY),
        is_experimental: false,
      },
    },
  ];

  return { type: 'FeatureCollection', features };
}
